apiVersion: maistra.io/v1alpha1
kind: ServiceMeshExtension
metadata:
  name: header-append
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: backend
  config: test
  image: quay.io/maistra-dev/header-append-filter:latest
  phase: PostAuthZ
  priority: 100
